# Usando uma imagem base do OpenJDK
FROM openjdk:17-jdk-slim

# Definindo o diretório de trabalho no container
WORKDIR /app

# Copiar o JAR compilado para dentro do container
COPY target/clientmanager-0.0.1-SNAPSHOT.jar app.jar

# Comando para executar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]

# Expondo a porta em que a aplicação Spring Boot estará rodando (padrão 8080)
EXPOSE 8080
